export const ROUTES = {
  LOGIN: 'login',
  REGISTER: 'register',
  FORGOTPASSWORD: 'forgotpass',
  PASSWORDSCREEN: 'passwordscreen',
  AUTH: 'auth',
  TABS: 'tabs',
  LANGUAGE: 'language',
  EnterAdCode: 'EnterAdCode',
  ONBOARDINGLOGIN: 'OnboardingLogin',
  VERIFICATION: 'Verification',
  ONBORDERPERSOM: 'OnborderPerson',
  Screens: 'Screens',
  HOME: 'Home',
  SELECTTYPE: 'SelectType',
  EDUCATIONCENTER: 'EducationalCenter',
  STUDENT: 'Student',
  TEACHER: 'Teacher',
  RECOVERYCODE: 'RecoveryCode',
  RECOVERY_EMAIL: 'RecoveryEmail',
  FAVORITES: 'FavoritesScreen',
  PROFILE: 'Личные данные',
  CATALOG: 'CatalogScreen',
  BALANSE: 'BalanseScreen',
  ProfileScrenEditing: 'ProfileScrenEditing',
  CHAT: 'Chat',
  BALANESNAVIGATION: 'BalanesNavigation',
  TEACHERNAVIGATION: 'TeacherNavigation',
  EDUCATIONALCENTERVIGATION: 'EducationNavigation',
  STUDENTNAVIGATION: 'StudentNavigation',
  REVIEWS: 'ReviewsScren',
  CHATTEACHER: 'ChatTeacher',
  CHECKERBOARD: 'Checkerboard',
  TeacherProfileScren: 'TeacherProfileScren',
  TeacherInfo: 'TeacherInfo',
  TeacherProfileNovigation: 'TeacherProfileNovigation',
  TeacherEditingProfile: 'TeacherEditingProfile',
  TeacherChatGroup: 'TeacherChatGroup',

  TeacherChooseChat: 'TeacherChooseChat',
  Notification: 'Notification',
  PaidService: 'PaidService',
  Transaction: 'Transaction',
  ReviewAllComponent: 'ReviewAllComponent',
  CenterProfile: 'CenterProfile',
  EducationChat: 'EducationChat',
  EducationChatGroup: 'EducationChatGroup',
  EducationChooseChat: 'EducationChooseChat',
  TeacherInfoScreen: 'TeacherInfoScreen',
  EducationBalansScreen: 'EducationBalansScreen',
  CategoriesAllScreen: 'CategoriesAllScreen',
  CategoriesCartInfo: 'CategoriesCartInfo',
  CategoriesCartInfoItem: 'CategoriesCartInfoItem',
  CategoriesSetting: 'CategoriesSetting',
  ServiceNewAll: 'ServiceNewAll',
  NewsCartInfo: 'NewsCartInfo',
  StudentInfoScreen: 'StudentInfoScreen',
  StudentReviews: 'StudentReviews',
  OurExpertAll: 'OurExpertAll',
  ModalLeft: 'ModalLeft',
  StudentChatGroup: 'StudentChatGroup',
  StudentChooseChat: 'StudentChooseChat',
  ERROR: '/error',
};
export enum APP_ROUTES {
  AUTH = '/auth',
  HOME = '/',
  LOGIN = '/auth/login',
  LOGIN_NEW_PASS = '/auth/login-new-pass',
  REGISTER = '/auth/sign-up',
  SIGN_UP_GET_CODE = '/auth/sign-up-get-code',
  MAILS_VIEW = '/mails',
  COURIERS_VIEW = '/couriers',
  ENTER_VIEW = '/enter',
  OUTPUT_VIEW = '/output',
  CALCULATIONS_VIEW = '/calculations',
  DASHBOARD_VIEW = '/dashboard',
  YUZK_VIEW = '/100k',
  MAILS_INFO_VIEW = '/mails-info',
  ADD_MAIL_VIEW = '/add-mail',
  ADDED_MAIL_VIEW = '/added-mail',
  IN_ENTER_VIEW = '/in-enter',
  SIDEBAR = '/sidebar',
  ERROR = '/error',
}
